updating up to python 3.11
geoadmin/lib-gatilegrid pull request #37
Opened 2023-05-23 09:56 UTC by rebert

2023-05-24 12:21 UTC, ltclm commented
does that mean that all the projects here:
https://github.com/search?q=org%3Ageoadmin%20gatilegrid&type=code
have to be updated to python3.11 (including prewarm.py on geodatasync, etc.)?

If yes i would prefer to go to python3.9 instead which is available on our infra.

2023-05-24 13:48 UTC, procrastinatio requested changes
As the code is published on `pypi`, I would be extremly conservative regarding what version to keep and ditch.

2023-05-24 13:48 UTC, procrastinatio commented on gatilegrid/__init__.py
> -from .grid import Grid
Why removing `Grid`?

2023-05-24 13:48 UTC, procrastinatio commented on setup.py
> +    version='0.2.1',
If you remove `python2`, I would bump the version a bit more

2023-05-25 07:24 UTC, rebert commented on gatilegrid/__init__.py
> -from .grid import Grid
as it is not being used

2023-05-25 11:08 UTC, procrastinatio commented
@ltclm Most project use a pinned version of the library, so it should'nt be an issue.

2023-05-25 11:10 UTC, procrastinatio approved these changes
OK, if you want. Do not forget to publish to `PyPi`

2023-05-25 12:18 UTC, closed without merging